EQMacEmu/Server

- common/database.cpp
- common/ruletypes.h
- world/clientlist.cpp
- zone/client_packet.cpp
- zone/entity.cpp
- zone/spell_effects.cpp
- zone/spells.cpp
- zone/waypoints.cpp
- zone/zone.cpp
- zone/zonedb.cpp
* Added demonstar's memleak fix for groups and raids.
Slightly edited it for performance.
* Added a GM no combat range feature to be expanded on.
> * Added some performance tweaks based on cppcheck results.

- common/eq_packet.cpp
- zone/waypoints.cpp
Applied a couple fixes to avoid dereferencing a NULL pointer.
> Reverted a change with failed logic.

- common/eq_packet.cpp
- zone/command.cpp
> Removed a wrong pointer check from a previous PR I did.

- zone/pathing.cpp
you now have to make a folder in the server dir called "newmaps"
it will save the file as a .path there is no need to add .path to the process.
So usage is #path process poknowledge
This will create a poknowledge.path in newmaps.
> Refined #path process a bit.

- utils/updateserver/EQServer.sh
- utils/updateserver/cron_scripts/server_reboot_10min.sh
- utils/updateserver/tak_checkout
- zone/command.cpp
- zone/command.h
This will fire off a 10 min warning broadcast and then update git, build and start server.
Included needed scripts to facilitate this. All in utils/updateserver folder. Usernames and passwords need to be set.
* Renamed #questupdate to #updatequests to have all server update commands grouped together.
* Added a output to the client of exactly what #updatequests has done.
> * Added #updatesource

- zone/inventory.cpp
- zone/npc.cpp
http://www.takproject.net/forums/viewtopic.php?f=7&t=2122
Bug: Wrong Pickpocket level check.
http://www.takproject.net/forums/viewtopic.php?f=7&t=2128
Enhancement: Bard instrument autoequip check.
> 2 Server Bugs - Review

- zone/groups.cpp
Bard Beneficial range.
http://www.takproject.net/forums/viewtopic.php?f=7&t=2180
Bard song should have ranges too..
> Bard Beneficial Song Range Fix

- zone/command.cpp
- zone/command.h
- For viewing bug reports in game on GMs.
- Based the status level off of EQ Support staff level so petitions can be compared to bugs.
> Added #bug

- zone/mob.cpp
I would guess that BestZ would do bad things in kedge.  This prevents Z decreasing, but it does cause the player to rise and fall two units on the client when pushed.
> New GetPushHeadingMod(), BestZ replaced with Z+2 in combatpush and knockback routines

- common/eq_packet_structs.h
- common/patches/mac_structs.h
I missed a struct change to a float for the client push code.  So here it is now.  Yes, I am still learning to use git.
> Structure changes to support client push.

- zone/aggro.cpp
- zone/client_packet.cpp
- zone/mob.cpp
- zone/mob.h
- zone/npc.cpp
- zone/pets.cpp
Added corrections for clients z positions.  This should make clients
bounce less and improve line of sight checks between clients and mobs.
> z_offset adjustments

- zone/mob_ai.cpp
- zone/waypoints.cpp
Fixed movement speed not being set for clients when under AI control.
> Fear fixes for clients.

- common/patches/mac.cpp
- common/ruletypes.h
- zone/aggro.cpp
- zone/client.cpp
- zone/client.h
- zone/client_packet.cpp
- zone/client_process.cpp
- zone/command.cpp
- zone/fearpath.cpp
- zone/lua_general.cpp
- zone/map.cpp
- zone/map.h
- zone/mob.cpp
- zone/mob.h
- zone/mob_ai.cpp
- zone/npc.cpp
- zone/npc.h
- zone/pathing.cpp
- zone/pets.cpp
- zone/questmgr.h
- zone/spell_effects.cpp
- zone/waypoints.cpp
- zone/zone.cpp
Changed mob speed calculations to round like the client.
Merged z offset corrections.
Fixed small races falling through the world so much.
> Updated mob speed calculations.

- common/patches/mac.cpp
- zone/client_packet.cpp
- zone/mob.cpp
Fixed z_pos issues by correcting rounding issues due to int math.
> Z fixes for bouncing ... again

- zone/client_packet.cpp
- zone/mob.cpp
- zone/waypoints.cpp
Forces a mob update being sent, with mobs on the move that change headings, or start new movements.
> More mob position updates

- zone/client_packet.cpp
- zone/entity.cpp
- zone/entity.h
- zone/hate_list.cpp
- zone/mob.cpp
- zone/mob.h
- zone/mob_ai.cpp
- zone/spells.cpp
- zone/waypoints.cpp
Optimized mob positions for mobs on the move at far distances.
Fix for assisting mobs in the zone, which allows targeting mob at a large range.
Fix for mobs who start to flee, being confused as feared, by NPCs/Pets.
> Mob position updates, bug fixes.

- world/client.cpp
- zone/client.cpp
- zone/client_packet.cpp
- zone/client_process.cpp
- zone/command.cpp
- zone/mob.cpp
- zone/mob.h
- zone/mob_ai.cpp
- zone/waypoints.cpp
- zone/zoning.cpp
Removed some duplicate packets being sent to clients for moving mob position updates.
Added some more optimizations in mob position updates, reducing number of unnecessary packets being sent to clients (up to 50% reduction in data being sent to clients).
Fixed some minor memory leaks, where some function return paths missed deletes.
> Bug fixes and Mob position update optimizations

- zone/bonuses.cpp
- zone/client_packet.cpp
- zone/common.h
- zone/mob.h
- zone/mob_ai.cpp
- zone/spell_effects.cpp
- zone/spells.cpp
Bard songs will now store the instrument mods with the buff. when a song begins or is pulsed.  The stored instrument mod will persist when the song is stopped.
> Bard songs will now store the instrument mods with the buff.

- loginserver/client.cpp
- loginserver/database.cpp
- loginserver/database.h
- loginserver/world_server.cpp
- This is step two of the overhaul of sql and options.
* Discovered a debug assertion that existed prior to this overhaul.
- Included some notes and commented debug items for this issue to be worked on later.
> * Redid how we write and handle sql in the loginserver.

- zone/attack.cpp
- zone/command.cpp
Fixed a crash in Mob::AvoidDamage with block skill
> #aggrozone command can now be used on a target

- loginserver/server_manager.cpp
- world/cliententry.cpp
- world/login_server.cpp
The server select screen will show servers with no zones up as DOWN.
Fixed a bug where number of players on server for webserver update gets off.
> The server select screen will now show LOCKED servers.

- zone/client.cpp
- zone/client.h
- zone/client_packet.cpp
- zone/command.cpp
- zone/entity.cpp
- zone/entity.h
- zone/mob.cpp
- zone/pathing.cpp
- zone/pathing.h
Increased range of client and npc updates.
Filtered some redundant client updates.
> Pathing Improvements.

- common/database.cpp
- common/database.h
- common/database_updates.cpp
- world/clientlist.cpp
This reverts commit bfa463d32a599f7d9a521ef4e971d768b0f6b81f.
> Revert "Added exemption check to max client per IP."

- loginserver/database.cpp
- loginserver/database.h
Changed initial loading of login.ini file settings to occur when new login settings table is created.
> Loginserver

- common/database.cpp
- common/database.h
- common/servertalk.h
- loginserver/client.cpp
- loginserver/server_manager.cpp
- loginserver/server_manager.h
- loginserver/world_server.cpp
- world/client.cpp
- world/cliententry.cpp
- world/clientlist.cpp
- world/clientlist.h
- world/login_server.cpp
- zone/mob.cpp
- zone/mob_ai.cpp
- zone/spells.cpp
IP limits and Account limits integrated into loginserver/worldserver communication.
Added messages to indicate when you have exceeded the IP limit, or you currently have a character in world, which would prevent logging in.
Fixed some issues with ghosting mob positions associated with stun/unstun and fleeing slowly.
> Loginserver IP/Account limits and mob ghosting fixes.

- common/eq_packet_structs.h
- common/patches/mac_structs.h
- world/client.cpp
- world/clientlist.cpp
- world/clientlist.h
- zone/client.cpp
- zone/client.h
- zone/client_packet.cpp
- zone/mob.cpp
- zone/waypoints.cpp
Added calculations for converting incoming and outgoing delta's.
IP Exemption checks changed to be against chars in zone or zoning.  This will make it friendlier if you crash getting to the character select screen.
> Corrected SpawnPositionUpdate_Struct for position deltas (-padding)

- world/client.cpp
- world/clientlist.cpp
- world/clientlist.h
Fixed issues with zoning and checking account active.  This caused getting dumped to server select when zoning.
> Bug fixes.

- common/eq_packet_structs.h
- zone/client.cpp
- zone/client.h
- zone/client_packet.cpp
- zone/client_process.cpp
- zone/entity.cpp
- zone/entity.h
- zone/mob.cpp
- zone/mob.h
- zone/spells.cpp
- zone/string_ids.h
- zone/waypoints.cpp
- zone/zone.cpp
- zone/zone.h
Reduced ghosting and packet updates outside of zone clip plane.
Targeting updates to help prevent clients target going bad.
> Client position updates.

- common/SocketLib/MemFile.cpp
- common/StackWalker/StackWalker.cpp
- common/emu_tcp_connection.cpp
- common/eq_stream.cpp
- common/eq_stream_ident.cpp
- common/item.cpp
- common/item.h
- common/misc.cpp
- common/proc_launcher.cpp
- common/shareddb.cpp
- common/string_util.cpp
- common/uuid.cpp
- world/login_server.cpp
Ones I didn't know how to handle I made comments detailing output of the scan.
> A few mem fixes

- zone/client.cpp
- zone/client.h
- zone/client_packet.cpp
apply poison fix didn't seem to merge right last go around....
> removed orphan code,

- zone/entity.cpp
- zone/mob_ai.cpp
- zone/waypoints.cpp
Fix for launches not moving right away after dropping grid.
> Fix for corpses not sending position updates.

- zone/entity.cpp
Missed a couple of paths that needed flag set for when spawn packet not sent.
> SpawnPacket fixes. 

- zone/entity.cpp
- zone/object.cpp
- zone/object.h
Ground items that are picked up, will no longer automagically reappear just by zoning out and back in.
> Ground Item Fixes

- zone/mob_ai.cpp
Fixed clients warping all over while feared in zones without pathing nodes.
> Client AI improvements.

- common/patches/trilogy.cpp
- common/patches/trilogy_structs.h
- zone/client.cpp
- zone/client_packet.cpp
Mob spawn improvements.
Mob animation type improvements when spawning (no more spread eagle spawns).
Mob respawns now work correctly.
Improved zoning, but requires static zones.  Dynamic zones currently do not start up fast enough and can mess up client connection.
> Fixed #zone command.

- common/patches/trilogy.cpp
Fixed issue with item packets sent too big.
> Items will now show worn, cast and proc effects in item description.

- common/patches/mac.cpp
- common/patches/mac_structs.h
- zone/attack.cpp
- zone/spell_effects.cpp
- zone/spells.cpp
- zone/trap.cpp
Fixed some angles associated with spell pushback and pushup.
Fixed a couple of potential memory leaks.
> Fixed SE_Tossup on clients

- common/guild_base.cpp
- world/client.cpp
- zone/mob.cpp
Adjusted mob positions int conversion for rounding.
Fixed issue sending guild list, so it begins at index 1.
Fixed character creation issue for dwarfs.
> Trilogy Fixes

- zone/client_packet.cpp
Fixed issue with anon flag in ServerZoneEntry.
> Fixed issue with GM flag being set in ServerZoneEntry.

- common/ruletypes.h
- loginserver/server_manager.cpp
- zone/mob.cpp
- zone/npc.cpp
- zone/queryserv.cpp
- zone/queryserv.h
- zone/spells.cpp
* make loginserver log message better
* fix compiler warning
* dont push npc's if perma rooted
> Rebase squish changes for upstream
