EQMacEmu/Server

- common/features.h
- zone/command.cpp
- zone/command.h
- Cleaned up the help for it.
- Added a corpse locator.
- Consolidated list into one sub command.
- Moved buried corpse commands to #corpse as a sub command.
- Fixed spelling on buried.
- Lowered the hard code admin check to match takp's adjustments.
> Reorganized #corpse command

- common/spdat.cpp
- zone/attack.cpp
- zone/mob_ai.cpp
Direct damage spells with a dispel component will now partial hit. (i.e. dragon aoes)
Lifetap spells will now partial hit.
Damaging spells with skill type 52 (tiger claw) will now send skill type 24 (evocation) in the packet.
NPCs will no longer stop casting offensive spells when their mana is below 10%, but will only cast spells they have the mana for.
> Dragon AoE partials, lifetap partials, skill type 52 fix

- common/features.h
- zone/command.cpp
- zone/zonedb.cpp
- zone/zonedb.h
Adjusted hard code statuses to match the database as defaults.
Alpha'd a few commands that were out of place,
adjustments to descriptions,
Added self only versions of a number of commands with a dual status check
and auto create of db entries for high range check of status.
- Invul
- Heal
- Mana
- Level
- GMSpeed
The old status values still are valid, they just turn into the low range (self only).
The values added are suffixed with a 2 automagically and set the high range to 250 by default.
The high values can be changed on the fly without a server reboot.
Also changed status check to bypass server level max to 250.
> Commands restructure and

- common/eqemu_config.h
- zone/embperl.cpp
- zone/lua_parser.cpp
- This is to minimize the new server setup steps needed to get started.
- It seems globals was already relocated prior.
> * Adjusted the hard coded location for reading lua_modules and plugins.

- common/ruletypes.h
- zone/attack.cpp
- zone/tune.cpp
Added new rule: RULE_BOOL (Combat, NewACCurves, true) for new AC client mitigation curves, that are more responsive to change in AC.  The shape of the curves is like as seen on EQLive. This is only applied to damage taken by clients.
> New Rule: RULE_BOOL (Combat, NewACCurves, true) for new AC mitigation

- zone/client_packet.cpp
Zoning in liquid, will no longer correct z for bestz.  This fixes qcat zoning issues.
> Zoning In liquid Z fixes.

- zone/attack.cpp
- zone/client_packet.cpp
- zone/client_process.cpp
- zone/string_ids.h
Added a fix for client freezing while scribing a spell and the spell was swapped in inventory for another spell.
Dropping an item into your inventory during casting a spell, will no longer cause an immediate disconnect from the server.  You have been warned.  Stand there and die like the rest of us.
Increased mitigation for silk wearers, based on defense skill.  This is based on formulas provided by SOE on mitigation calculations.
> Bug fixes.  Silk wearing mitigation boost.

- zone/entity.cpp
- zone/entity.h
- zone/spell_effects.cpp
Any NPCs casting a spell on a charmed NPC, when charm breaks, will now have their spells interrupted.
> Bug fix where charmed mobs can cause faction wars.

- zone/command.cpp
- zone/pathing.cpp
- zone/pathing.h
#path meshtest, will now required a 2nd parameter, simple or complex.  Using #path meshtest simple will now feedback information directly to the client.
#path dump <filename> will resort connections and nodes, prior to saving.  This will help prevent saving unsorted pathnodes, which will cause the path to be unusable.
#path move, will move the selected node visibly to your location.  This will also update distances from this node to the neighbors.  And neighbors to this node.  Without the distance update, this would almost always break paths at finding shortest distance paths, if a node was ever moved.
#path remove, will remove the selected node visible in the zone.  You must use #path resort nodes, prior to using the pathing, or the zone will likely crash.  Following removal of the node, …
> Pathing Tools Improvements.

- zone/attack.cpp
- zone/tune.cpp
Simplified softcap calculation so it scales better with level.  Previous calculation blew up very large at higher levels, so it was not capping anything.
> Simplified AC Softcap calculation.

- zone/attack.cpp
- zone/client.h
- zone/client_mods.cpp
- zone/tune.cpp
Adjusted AC bonus from spells (lower) and defense skills (higher for cloth classes), based on SOE dev post on AC mitigation calculations.
Softcap calculation adjusted to values that scales better with level and skill.
Overall, increased mitigation effects at the lower levels.
> Client AC mitigation adjustments.

- zone/client_packet.cpp
- zone/mob.cpp
- zone/mob.h
- zone/mob_ai.cpp
- zone/waypoints.cpp
Moved z_offset to be precalculated when size is set/changed.
Added z_offset to diff z checks for when z needs adjusted during pathing/moving.  Mobs that are larger size, can be off more, and need adjusted.
Moved pets to walk at their owners walk speed, to make their movement while following smoother.
Pets will now have slightly different distances to when they start to follow their owners and when they catch up.  That way pets are not starting/stopping so much and sending more position update packets.
Pets at a distance will now send their position updates out to everyone less frequently.
When x and y are calculated in a roam box, the z will use the bestz at that location, rather than GetZ().  This helps prevent mobs on the move from bouncing up and down as often.
> Mob position update optimizations.

- zone/object.cpp
Stationary ground spawns will now visibly re-spawn for client that is in the zone.  You will no longer have to rezone, for them to appear.
> Stationary ground spawns will now visibly re-spawn for a client in the zone.

- common/eq_packet_structs.h
- common/patches/mac.cpp
- common/patches/mac_structs.h
- zone/attack.cpp
- zone/client_packet.cpp
- zone/fearpath.cpp
- zone/mob_ai.cpp
Added a buffer outside range of max clip for targeting.  The client allows targeting just outside of the clip plane, if a mob was right where you clicked.  This will prevent the target from becoming invalid, and causing you to have to re-target the mob to attack.
Removed the delta for pet following that was in last patch.  It did not work very well anyways.
If you FD while on the rampage list, you will no longer get hit.  The rampage will go on to the next person in rampage order.  The FD person will not be removed from the list, so if they get back up, stand by to continue to take rampage.
If a mob is casting a spell, they will not process a flee check until finished casting.  This prevents some abnormal behavior, if that spell was a heal on them, and would have put them above the point …
> Targeting fix.  FD taking Rampage damage fix.  Mob fleeing behavior fix.

- common/eq_packet_structs.h
- common/patches/mac.cpp
- common/patches/mac_structs.h
- zone/spells.cpp
Moved simple push on clients from spells, like Force of Ykesha to the action packet.  This prevents clients that are moving, from warping backwards, when the spell lands.
> Simple spell push on clients moved to action packet.

- common/database.cpp
- common/eq_stream.cpp
- common/eq_stream_factory.h
- world/client.cpp
- world/clientlist.cpp
- zone/client_process.cpp
- zone/mob_ai.cpp
Fixed a bug where the universal chat server address would not be upda…ted when logging in.
Reduced timeout for when network closes after a client crashes, after which the LD timer starts.  I would previously take over 2 minutes, before the LD process would start after a crash.
Going LD without aggro will not be as severe, the lockout will be similar to camping.
Camping normally will take you to the server select screen again.
> LD and Camping fixes and improvements.

- zone/client_process.cpp
Changed disconnect for camping so it no longer shows a message that you were disconnected.
> Changed disconnect process for camping

- zone/mob_ai.cpp
NPCs will start updating positions quicker when they start moving from a pause.  This will help prevent ghost mobs being in false locations due to previous movement.
> NPCs will start updating positions quicker when they start moving.

- loginserver/login_structures.h
- loginserver/server_manager.cpp
- world/cliententry.cpp
- zone/client.cpp
- zone/string_ids.h
Server option of showusercount will now work, when set to a value other than zero.  This is currently coded to show servers as UP, rather than number of users.  The number of users was being sent in wrong location of struct before.
Server user count now updates based in being in zone, rather than just at char select screen.  Values should now be accurate.
Sending a tell to a corpse with /ttell will now relay it to their owner.
> Fixed a bug where the server list sometimes doesn't show.

- zone/client_process.cpp
- zone/mob.cpp
- zone/mob_ai.cpp
When a mob starts to flee, they will now show that they are fleeing immediately, rather than warping to their first update.
When a mob is snared, they will immediately show their speed change.
> Mob position update improvements to reduce lag/disconnects.

- zone/corpse.cpp
Bags on a corpse containing lore items you already possess, will no longer be lootable.
> Fix for looting bags containing lore items you already have.

- zone/attack.cpp
Fix for potential crashes in Mob::AvoidDamage due to uninitialized variable being used.
This was also preventing NPCs from getting their skill for block, parry, and dodge applied their chance to perform.
> Fix for potential crashes in Mob::AvoidDamage

- common/eq_packet.cpp
- zone/aggro.cpp
- zone/mob.cpp
- zone/mob.h
- zone/pathing.cpp
Culling of path nodes at back of route, will no longer force a path update every time the destination changes.
During AI yell for help, NPCs that already have the target on their hate list will be skipped during checks.
> Added some checks in packet decoding for bad packets.

- zone/command.cpp
- zone/pathing.cpp
- zone/pathing.h
Added option to #path shownodes [around].  This will only show nodes around you at a range of 200.  Useful when there are very large numbers of nodes in a zone.
When loading paths, the distances between neighbors will be recalculated.  Previous path code did not update distances, when nodes were moved.  So these could be off.
Distances between nodes will be pre-calculated when paths are loaded.  These distances will be used to weight the nodes when calculating pathing.
Improved update path logic, to first try and cull a node on the tail, if target has moved closer, rather than recalculate entire path by default.
> Pathing Optimizations

- zone/entity.cpp
- zone/pathing.cpp
- zone/pathing.h
When #path meshtest simple is run.  First disconnected node will be auto targeted.
Running #path nearest all, first mob not finding a nearby node will be auto targeted.
> Pathing fixes and improvements.

- world/clientlist.cpp
Fixed issue where stale ClientListEntry was clearing active accounts, allowing multiple characters logged in from same account.
> Fixed issue where stale ClientListEntry was clearing active accounts.

- zone/waypoints.cpp
Fixed leaving grid waypoints to only send one update packet.  It was sending 2 extra position update packets unnecessarily.
> Fixed an issue that caused 3 pos updates after leaving grid wp.

- zone/mob_ai.cpp
- zone/pathing.cpp
Mobs that rotate to flee, when snared to a stop, will face first node in their path, if the zone has pathing.
> Rotating updates.

- zone/entity.cpp
- zone/mob.cpp
- zone/mob.h
- zone/mob_ai.cpp
Added delays to performing SPAWN events, until after the spawn packet is sent for NPCs.
SPAWN emotes will now be sent after spawn packets are sent.
Fixed random delay in starting spell casting for NPCs on spawn (this was added before, but didn't actually work).
> Spawn Packet timing changes.

- common/patches/trilogy_structs.h
- zone/client_packet.cpp
Fixed LootingItem_Struct.
Fixed checks against size of OP_EndLootRequest.  This should allow looting items from NPC corpses.
> Looting item fixes.

- common/eq_stream.cpp
- zone/mob.cpp
- zone/spell_effects.cpp
Players that have charmed mobs targeted, will no longer have their target go invalid after charm breaks.  No more re-targeting required.
Moved some log support code inside the logic if that logging is on for packets.  That way the check is only performed during logging, not every single packet.
> Charm Fixes.

- common/eq_stream.cpp
Moved some logic for some extra checks associated with logging.
Server to Client packet logging, will now show the actual opcode along with the translated name.  The emu opcode was shown before, which provided no value added.
> Packet Logging improvements.

- common/eq_packet_structs.h
- common/patches/trilogy.cpp
- common/patches/trilogy_structs.h
- zone/client_packet.cpp
- zone/entity.cpp
- zone/entity.h
Added trilogy door struct.
Updated door click struct for trilogy.
Updated bulk sending doors for trilogy.
OP_ManaUpdate updated for trilogy.  When only updating mana value,  it accepts a size 2 packet, without a spellid  (eqmac looks to support this too).
> Door and Mana updates.

- common/eq_packet_structs.h
- common/patches/mac.cpp
- zone/client_packet.cpp
- zone/mob.cpp
- zone/zoning.cpp
Client and Server will round their positions the same way now, when converting x and y coordinates from float to int.
Changed encoding for ServerZoneEntry_Struct to be direct, so as to not round positions and heading.  This helps prevent client loc and heading changing when logging in.
Fixed an issue with the z adjustment for clients, using zone geometry when logging in.  It was not updating correctly based on the real value for bestz.
> Fixed some rounding issues with clients vs server locs.
